// Generated by scripts/build.mjs. Do not edit by hand.
const VERSION = 'a79f130215'
const FILES = [
  "./",
  "content/index.js",
  "content/m00-practice.js",
  "content/m01-rapport.js",
  "content/m02-calibration.js",
  "content/m03-pacing-leading.js",
  "content/m04-vague-language.js",
  "content/m05-links-causes.js",
  "content/m06-nuvi.js",
  "content/m07-presuppositions.js",
  "content/m08-embedded-commands.js",
  "content/m09-stories.js",
  "content/m10-utilization.js",
  "content/m11-imagery.js",
  "content/m12-framing.js",
  "content/m13-precision-questions.js",
  "content/m14-commitment.js",
  "content/m15-whole-conversation.js",
  "content/reference.js",
  "icons/apple-touch-icon.png",
  "icons/icon-192.png",
  "icons/icon-512.png",
  "icons/icon.svg",
  "index.html",
  "manifest.webmanifest",
  "src/app.js",
  "src/md.js",
  "src/progress.js",
  "src/store.js",
  "src/styles.css",
  "src/words.js"
]

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(VERSION).then((c) => c.addAll(FILES)).then(() => self.skipWaiting()))
})

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys().then((keys) => Promise.all(keys.filter((k) => k !== VERSION).map((k) => caches.delete(k)))).then(() => self.clients.claim())
  )
})

// Pages: network first, so a new version arrives when there is a connection.
// Everything else: the cache, which is replaced whole when the version changes.
self.addEventListener('fetch', (e) => {
  const url = new URL(e.request.url)
  if (e.request.method !== 'GET' || url.origin !== location.origin) return
  if (e.request.mode === 'navigate') {
    e.respondWith(fetch(e.request).catch(() => caches.match('./')))
    return
  }
  e.respondWith(caches.match(e.request, { ignoreSearch: true }).then((hit) => hit ?? fetch(e.request)))
})
