// Writes sw.js with the list of files to keep offline and a version taken
// from their contents, and stamps that version on index.html. Run after any
// change, before committing: node scripts/build.mjs  (--check exits 1 if stale)
import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs'
import { createHash } from 'node:crypto'
import { join } from 'node:path'

const walk = (dir) =>
  readdirSync(dir).flatMap((f) => {
    const p = join(dir, f)
    return statSync(p).isDirectory() ? walk(p) : [p]
  })
const files = [
  'index.html',
  'manifest.webmanifest',
  ...walk('src'),
  ...walk('content').filter((f) => f.endsWith('.js')),
  ...walk('icons'),
  ...walk('fonts').filter((f) => f.endsWith('.woff2')),
].sort()

const hash = createHash('sha256')
for (const f of files) {
  hash.update(f)
  hash.update(f === 'index.html' ? readFileSync(f, 'utf8').replace(/data-version="[^"]*"/, '') : readFileSync(f))
}
const version = hash.digest('hex').slice(0, 10)

const sw = `// Generated by scripts/build.mjs. Do not edit by hand.
const VERSION = '${version}'
const FILES = ${JSON.stringify(['./', ...files], null, 2)}

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(VERSION).then((c) => c.addAll(FILES)).then(() => self.skipWaiting()))
})

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys().then((keys) => Promise.all(keys.filter((k) => k !== VERSION).map((k) => caches.delete(k)))).then(() => self.clients.claim())
  )
})

// Pages: network first, so a new version arrives when there is a connection.
// Everything else: the cache, which is replaced whole when the version changes.
self.addEventListener('fetch', (e) => {
  const url = new URL(e.request.url)
  if (e.request.method !== 'GET' || url.origin !== location.origin) return
  if (e.request.mode === 'navigate') {
    e.respondWith(fetch(e.request).catch(() => caches.match('./')))
    return
  }
  e.respondWith(caches.match(e.request, { ignoreSearch: true }).then((hit) => hit ?? fetch(e.request)))
})
`
const html = readFileSync('index.html', 'utf8').replace(/data-version="[^"]*"/, `data-version="${version}"`)

if (process.argv.includes('--check')) {
  const stale = readFileSync('sw.js', 'utf8') !== sw || readFileSync('index.html', 'utf8') !== html
  if (stale) {
    console.error('sw.js or index.html is stale: run node scripts/build.mjs')
    process.exit(1)
  }
  console.log(`up to date (${version})`)
} else {
  writeFileSync('sw.js', sw)
  writeFileSync('index.html', html)
  console.log(`version ${version}, ${files.length} files`)
}
